version: '2.0'
services:
  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - dbdatavol:/var/lib/postgresql/data
    ports:
      - "5433:5432"
volumes:
  dbdatavol:
    driver: local