version: '2.0'
services:
  postgres:
    restart: always
    image: mdillon/postgis
    volumes:
      - dbdatavol:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  dbdatavol:
    driver: local